<?php

declare(strict_types=1);

namespace Gumslone\Vulns\Support;

/**
 * A representative base vector for every base score a CVSS version can
 * produce — generated by enumerating every base vector (729 for v2, 2 592
 * for v3.1, 186 624 for v4.0) through the package's own calculators and
 * keeping, per distinct score, the first vector in preference order:
 * network-reachable, low complexity, unprivileged, no interaction, highest
 * impact. That makes the pick deterministic and the "obvious" vector for the
 * common scores (9.8 → AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H, 7.5 → …/C:H/I:N/A:N).
 *
 * Used to backfill a vector when a source publishes only a score. A score
 * has many vectors, so an inferred vector is an approximation — records
 * carrying one flag it in VulnerabilityData::$inferredFields.
 */
final class CvssVectorTable
{
    /** CVSS v2.0 base vectors (unprefixed, as NVD publishes them). */
    public const V2 = [
        '0.0' => 'AV:N/AC:L/Au:N/C:N/I:N/A:N',
        '0.8' => 'AV:L/AC:H/Au:M/C:P/I:N/A:N',
        '1.0' => 'AV:L/AC:H/Au:S/C:P/I:N/A:N',
        '1.2' => 'AV:A/AC:H/Au:M/C:P/I:N/A:N',
        '1.3' => 'AV:L/AC:M/Au:M/C:P/I:N/A:N',
        '1.4' => 'AV:A/AC:H/Au:S/C:P/I:N/A:N',
        '1.5' => 'AV:L/AC:M/Au:S/C:P/I:N/A:N',
        '1.7' => 'AV:N/AC:H/Au:M/C:P/I:N/A:N',
        '1.8' => 'AV:A/AC:H/Au:N/C:P/I:N/A:N',
        '1.9' => 'AV:A/AC:M/Au:M/C:P/I:N/A:N',
        '2.1' => 'AV:N/AC:H/Au:S/C:P/I:N/A:N',
        '2.2' => 'AV:A/AC:L/Au:M/C:P/I:N/A:N',
        '2.3' => 'AV:A/AC:M/Au:S/C:P/I:N/A:N',
        '2.4' => 'AV:L/AC:H/Au:S/C:P/I:P/A:N',
        '2.6' => 'AV:N/AC:H/Au:N/C:P/I:N/A:N',
        '2.7' => 'AV:A/AC:L/Au:S/C:P/I:N/A:N',
        '2.8' => 'AV:N/AC:M/Au:M/C:P/I:N/A:N',
        '2.9' => 'AV:A/AC:M/Au:N/C:P/I:N/A:N',
        '3.0' => 'AV:L/AC:M/Au:S/C:P/I:P/A:N',
        '3.2' => 'AV:N/AC:H/Au:M/C:P/I:P/A:N',
        '3.3' => 'AV:N/AC:L/Au:M/C:P/I:N/A:N',
        '3.4' => 'AV:A/AC:M/Au:M/C:P/I:P/A:N',
        '3.5' => 'AV:N/AC:M/Au:S/C:P/I:N/A:N',
        '3.6' => 'AV:N/AC:H/Au:S/C:P/I:P/A:N',
        '3.7' => 'AV:A/AC:L/Au:M/C:P/I:P/A:N',
        '3.8' => 'AV:A/AC:M/Au:S/C:P/I:P/A:N',
        '4.0' => 'AV:N/AC:L/Au:S/C:P/I:N/A:N',
        '4.1' => 'AV:A/AC:L/Au:S/C:P/I:P/A:N',
        '4.3' => 'AV:N/AC:M/Au:N/C:P/I:N/A:N',
        '4.4' => 'AV:L/AC:M/Au:N/C:P/I:P/A:P',
        '4.5' => 'AV:A/AC:M/Au:M/C:P/I:P/A:P',
        '4.6' => 'AV:N/AC:H/Au:S/C:P/I:P/A:P',
        '4.7' => 'AV:N/AC:L/Au:M/C:P/I:P/A:N',
        '4.8' => 'AV:A/AC:L/Au:N/C:P/I:P/A:N',
        '4.9' => 'AV:N/AC:M/Au:S/C:P/I:P/A:N',
        '5.0' => 'AV:N/AC:L/Au:N/C:P/I:N/A:N',
        '5.1' => 'AV:N/AC:H/Au:N/C:P/I:P/A:P',
        '5.2' => 'AV:A/AC:L/Au:S/C:P/I:P/A:P',
        '5.3' => 'AV:N/AC:H/Au:M/C:C/I:P/A:N',
        '5.4' => 'AV:N/AC:M/Au:M/C:P/I:P/A:P',
        '5.5' => 'AV:N/AC:L/Au:S/C:P/I:P/A:N',
        '5.6' => 'AV:N/AC:H/Au:S/C:C/I:P/A:N',
        '5.7' => 'AV:N/AC:M/Au:M/C:C/I:N/A:N',
        '5.8' => 'AV:N/AC:L/Au:M/C:P/I:P/A:P',
        '5.9' => 'AV:A/AC:M/Au:M/C:C/I:P/A:P',
        '6.0' => 'AV:N/AC:M/Au:S/C:P/I:P/A:P',
        '6.1' => 'AV:N/AC:L/Au:M/C:C/I:N/A:N',
        '6.2' => 'AV:N/AC:H/Au:M/C:C/I:C/A:N',
        '6.3' => 'AV:N/AC:M/Au:S/C:C/I:N/A:N',
        '6.4' => 'AV:N/AC:L/Au:N/C:P/I:P/A:N',
        '6.5' => 'AV:N/AC:L/Au:S/C:P/I:P/A:P',
        '6.6' => 'AV:N/AC:H/Au:N/C:C/I:P/A:P',
        '6.7' => 'AV:A/AC:L/Au:S/C:C/I:P/A:P',
        '6.8' => 'AV:N/AC:L/Au:S/C:C/I:N/A:N',
        '6.9' => 'AV:N/AC:M/Au:M/C:C/I:P/A:P',
        '7.0' => 'AV:N/AC:M/Au:S/C:C/I:P/A:N',
        '7.1' => 'AV:N/AC:M/Au:N/C:C/I:N/A:N',
        '7.2' => 'AV:A/AC:L/Au:M/C:C/I:C/A:C',
        '7.3' => 'AV:N/AC:L/Au:M/C:C/I:P/A:P',
        '7.4' => 'AV:A/AC:L/Au:S/C:C/I:C/A:P',
        '7.5' => 'AV:N/AC:L/Au:N/C:P/I:P/A:P',
        '7.6' => 'AV:N/AC:H/Au:N/C:C/I:C/A:C',
        '7.7' => 'AV:N/AC:L/Au:M/C:C/I:C/A:N',
        '7.8' => 'AV:N/AC:L/Au:N/C:C/I:N/A:N',
        '7.9' => 'AV:N/AC:M/Au:S/C:C/I:C/A:N',
        '8.0' => 'AV:N/AC:L/Au:S/C:C/I:P/A:P',
        '8.2' => 'AV:N/AC:M/Au:S/C:C/I:C/A:P',
        '8.3' => 'AV:N/AC:L/Au:M/C:C/I:C/A:C',
        '8.5' => 'AV:N/AC:L/Au:N/C:C/I:P/A:N',
        '8.7' => 'AV:N/AC:L/Au:S/C:C/I:C/A:P',
        '8.8' => 'AV:N/AC:M/Au:N/C:C/I:C/A:N',
        '9.0' => 'AV:N/AC:L/Au:N/C:C/I:P/A:P',
        '9.3' => 'AV:N/AC:M/Au:N/C:C/I:C/A:C',
        '9.4' => 'AV:N/AC:L/Au:N/C:C/I:C/A:N',
        '9.7' => 'AV:N/AC:L/Au:N/C:C/I:C/A:P',
        '10.0' => 'AV:N/AC:L/Au:N/C:C/I:C/A:C',
    ];

    /** CVSS v3.1 base vectors. */
    public const V3 = [
        '0.0' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N',
        '1.6' => 'CVSS:3.1/AV:P/AC:H/PR:H/UI:N/S:U/C:L/I:N/A:N',
        '1.7' => 'CVSS:3.1/AV:P/AC:L/PR:H/UI:R/S:U/C:L/I:N/A:N',
        '1.8' => 'CVSS:3.1/AV:A/AC:H/PR:H/UI:R/S:U/C:L/I:N/A:N',
        '1.9' => 'CVSS:3.1/AV:L/AC:H/PR:H/UI:N/S:U/C:L/I:N/A:N',
        '2.0' => 'CVSS:3.1/AV:N/AC:H/PR:H/UI:R/S:U/C:L/I:N/A:N',
        '2.1' => 'CVSS:3.1/AV:A/AC:L/PR:H/UI:R/S:U/C:L/I:N/A:N',
        '2.2' => 'CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:L/I:N/A:N',
        '2.3' => 'CVSS:3.1/AV:A/AC:H/PR:L/UI:R/S:U/C:L/I:N/A:N',
        '2.4' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:L/I:N/A:N',
        '2.5' => 'CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N',
        '2.6' => 'CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:U/C:L/I:N/A:N',
        '2.7' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:L/I:N/A:N',
        '2.8' => 'CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:L/I:N/A:N',
        '2.9' => 'CVSS:3.1/AV:A/AC:L/PR:H/UI:R/S:C/C:L/I:N/A:N',
        '3.0' => 'CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:C/C:L/I:N/A:N',
        '3.1' => 'CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N',
        '3.2' => 'CVSS:3.1/AV:A/AC:L/PR:H/UI:R/S:U/C:L/I:L/A:N',
        '3.3' => 'CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:L/I:L/A:N',
        '3.4' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:N/A:N',
        '3.5' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:N/A:N',
        '3.6' => 'CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:C/C:L/I:N/A:N',
        '3.7' => 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N',
        '3.8' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:L/I:L/A:N',
        '3.9' => 'CVSS:3.1/AV:N/AC:H/PR:H/UI:R/S:U/C:L/I:L/A:L',
        '4.0' => 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:N/A:N',
        '4.1' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:N/A:N',
        '4.2' => 'CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:L/A:N',
        '4.3' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:N/A:N',
        '4.4' => 'CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:C/C:L/I:L/A:N',
        '4.5' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:H/I:N/A:N',
        '4.6' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:N',
        '4.7' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:N/A:N',
        '4.8' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:N',
        '4.9' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N',
        '5.0' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:N/A:N',
        '5.1' => 'CVSS:3.1/AV:N/AC:H/PR:H/UI:R/S:C/C:L/I:L/A:L',
        '5.2' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:H/I:L/A:N',
        '5.3' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
        '5.4' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N',
        '5.5' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:L',
        '5.6' => 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:L',
        '5.7' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:N/A:N',
        '5.8' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:N/A:N',
        '5.9' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:L',
        '6.0' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:L/A:L',
        '6.1' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
        '6.2' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:H/I:N/A:N',
        '6.3' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L',
        '6.4' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N',
        '6.5' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N',
        '6.6' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:L/I:L/A:L',
        '6.7' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:L',
        '6.8' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:L/A:L',
        '6.9' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:H/I:L/A:N',
        '7.0' => 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:L/A:L',
        '7.1' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:L/A:N',
        '7.2' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:N',
        '7.3' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L',
        '7.4' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:N/A:N',
        '7.5' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
        '7.6' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:L/A:L',
        '7.7' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:N/A:N',
        '7.8' => 'CVSS:3.1/AV:A/AC:L/PR:H/UI:R/S:C/C:H/I:H/A:L',
        '7.9' => 'CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:C/C:H/I:H/A:L',
        '8.0' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H',
        '8.1' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:N',
        '8.2' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:N',
        '8.3' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:L',
        '8.4' => 'CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:H/I:H/A:H',
        '8.5' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:L/A:N',
        '8.6' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:L',
        '8.7' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:N',
        '8.8' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H',
        '8.9' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:L',
        '9.0' => 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:H',
        '9.1' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N',
        '9.2' => 'CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:L',
        '9.3' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:L/A:N',
        '9.4' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L',
        '9.6' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H',
        '9.8' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
        '9.9' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:L/A:L',
        '10.0' => 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H',
    ];

    /** CVSS v4.0 base vectors. */
    public const V4 = [
        '0.0' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:N/SC:N/SI:N/SA:N',
        '1.0' => 'CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:P/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N',
        '1.8' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:H/UI:A/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N',
        '2.0' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:A/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N',
        '2.1' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:A/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N',
        '2.3' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:P/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N',
        '2.4' => 'CVSS:4.0/AV:A/AC:L/AT:N/PR:L/UI:P/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N',
        '2.5' => 'CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:P/VC:L/VI:L/VA:L/SC:H/SI:H/SA:S',
        '2.7' => 'CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:P/VC:L/VI:L/VA:L/SC:H/SI:S/SA:S',
        '4.0' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:H/UI:A/VC:L/VI:L/VA:L/SC:N/SI:N/SA:H',
        '4.1' => 'CVSS:4.0/AV:A/AC:L/AT:N/PR:L/UI:P/VC:L/VI:L/VA:L/SC:N/SI:N/SA:H',
        '4.2' => 'CVSS:4.0/AV:A/AC:L/AT:N/PR:L/UI:P/VC:L/VI:L/VA:L/SC:N/SI:L/SA:H',
        '4.3' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:A/VC:L/VI:L/VA:L/SC:N/SI:N/SA:H',
        '4.4' => 'CVSS:4.0/AV:A/AC:L/AT:N/PR:L/UI:P/VC:L/VI:L/VA:L/SC:N/SI:H/SA:H',
        '4.5' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:A/VC:L/VI:L/VA:L/SC:N/SI:L/SA:H',
        '4.6' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:A/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N',
        '4.7' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:H/UI:A/VC:L/VI:L/VA:L/SC:L/SI:H/SA:H',
        '4.8' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:L/UI:A/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N',
        '4.9' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:P/VC:L/VI:L/VA:L/SC:N/SI:N/SA:H',
        '5.0' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:A/VC:L/VI:L/VA:L/SC:L/SI:H/SA:H',
        '5.1' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N',
        '5.2' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:A/VC:L/VI:L/VA:L/SC:H/SI:H/SA:H',
        '5.3' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N',
        '5.4' => 'CVSS:4.0/AV:A/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N',
        '5.5' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:A/VC:L/VI:L/VA:L/SC:H/SI:H/SA:H',
        '5.6' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:P/VC:L/VI:L/VA:L/SC:L/SI:H/SA:H',
        '5.7' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:A/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N',
        '5.8' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:P/VC:L/VI:L/VA:L/SC:H/SI:H/SA:H',
        '5.9' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:A/VC:L/VI:L/VA:L/SC:N/SI:N/SA:H',
        '6.0' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:L/UI:A/VC:L/VI:L/VA:L/SC:N/SI:N/SA:H',
        '6.1' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:L/VI:L/VA:L/SC:N/SI:N/SA:H',
        '6.2' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:L/VI:L/VA:L/SC:N/SI:L/SA:H',
        '6.3' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:L/VI:L/VA:L/SC:N/SI:N/SA:H',
        '6.4' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:L/VI:L/VA:L/SC:N/SI:H/SA:H',
        '6.5' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:L/VI:L/VA:L/SC:H/SI:H/SA:H',
        '6.6' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:L/VI:L/VA:L/SC:H/SI:H/SA:S',
        '6.7' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:A/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N',
        '6.8' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:L/UI:A/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N',
        '6.9' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N',
        '7.0' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:H/VI:L/VA:L/SC:N/SI:N/SA:N',
        '7.1' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:L/VA:N/SC:N/SI:N/SA:N',
        '7.2' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:L/VA:H/SC:N/SI:N/SA:N',
        '7.3' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:P/VC:H/VI:L/VA:H/SC:N/SI:H/SA:H',
        '7.4' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:P/VC:H/VI:L/VA:H/SC:H/SI:H/SA:H',
        '7.5' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:A/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N',
        '7.6' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:P/VC:H/VI:H/VA:L/SC:N/SI:N/SA:N',
        '7.7' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:H',
        '7.8' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA:L/SC:N/SI:L/SA:H',
        '7.9' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA:L/SC:L/SI:H/SA:H',
        '8.0' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA:L/SC:H/SI:H/SA:S',
        '8.1' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:A/VC:H/VI:L/VA:L/SC:N/SI:N/SA:H',
        '8.2' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:H/VI:N/VA:N/SC:N/SI:N/SA:H',
        '8.3' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:L/VA:N/SC:N/SI:N/SA:H',
        '8.4' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:L/VA:H/SC:N/SI:N/SA:H',
        '8.5' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:L/VA:H/SC:N/SI:H/SA:H',
        '8.6' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:H/VA:N/SC:N/SI:N/SA:N',
        '8.7' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N',
        '8.8' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:L/VA:H/SC:N/SI:N/SA:N',
        '8.9' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:H/VI:N/VA:N/SC:N/SI:N/SA:H',
        '9.0' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:H/VI:L/VA:H/SC:N/SI:N/SA:H',
        '9.1' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:A/VC:H/VI:H/VA:N/SC:N/SI:N/SA:H',
        '9.2' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:L/VA:H/SC:N/SI:N/SA:H',
        '9.3' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N',
        '9.4' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:H/VA:H/SC:L/SI:H/SA:H',
        '9.5' => 'CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:L/SA:H',
        '9.9' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:H',
        '10.0' => 'CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:L/SI:H/SA:H',
    ];

    /**
     * A base vector that scores exactly $score under the given CVSS major
     * version, or — when no base vector produces that score (a temporal or
     * environmental score, a rounding artefact) — the vector with the nearest
     * score. Null only for an unknown version or an out-of-range score.
     */
    public static function vectorFor(int $version, float $score): ?string
    {
        $table = self::table($version);
        if ($table === [] || $score < 0.0 || $score > 10.0) {
            return null;
        }

        $key = number_format($score, 1, '.', '');
        if (isset($table[$key])) {
            return $table[$key];
        }

        $best = null;
        $bestDistance = PHP_FLOAT_MAX;
        foreach ($table as $tableScore => $vector) {
            $distance = round(abs((float) $tableScore - $score), 3);
            // Ties resolve upward: over-estimating severity is the safe side.
            if ($distance < $bestDistance || ($distance === $bestDistance && (float) $tableScore > $score)) {
                $bestDistance = $distance;
                $best = $vector;
            }
        }

        return $best;
    }

    /** Whether some base vector produces exactly this score (no approximation). */
    public static function isExact(int $version, float $score): bool
    {
        return isset(self::table($version)[number_format($score, 1, '.', '')]);
    }

    /** @return array<string, string> */
    private static function table(int $version): array
    {
        return match ($version) {
            2 => self::V2,
            3 => self::V3,
            4 => self::V4,
            default => [],
        };
    }
}
